In [1]:
import sys
from pathlib import Path

# Set project root
PROJECT_ROOT = Path("C:/Users/A I TECH/Project/SentiCare-Capstone")
sys.path.insert(0, str(PROJECT_ROOT))

print("Project Root:", PROJECT_ROOT)

Project Root: C:\Users\A I TECH\Project\SentiCare-Capstone

In [2]:
import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt

from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Import ONLY from file
from preprocessing.pipeline import TherapeuticPreprocessor

In [3]:
DATA_PATH = PROJECT_ROOT / "data/raw/Enhanced_anxiety_dataset.csv"
TARGET = "Anxiety Level (1-10)"

df = pd.read_csv(DATA_PATH)

# Optional cleanup
df = df.drop(columns=["Heart Rate (bpm)"], errors="ignore")

print("Shape:", df.shape)
df.head()

Shape: (11000, 18)

,Age,Gender,Occupation,Sleep Hours,Physical Activity (hrs/week),Caffeine Intake (mg/day),Alcohol Consumption (drinks/week),Smoking,Family History of Anxiety,Stress Level (1-10),Breathing Rate (breaths/min),Sweating Level (1-5),Dizziness,Medication,Therapy Sessions (per month),Recent Major Life Event,Diet Quality (1-10),Anxiety Level (1-10)
0,29,Female,Artist,6.0,2.7,181,10,Yes,No,10,14,4,No,Yes,3,Yes,7,5.0
1,46,Other,Nurse,6.2,5.7,200,8,Yes,Yes,1,23,2,Yes,No,2,No,8,3.0
2,64,Male,Other,5.0,3.7,117,4,No,Yes,1,28,3,No,No,1,Yes,1,1.0
3,20,Female,Scientist,5.8,2.8,360,6,Yes,No,4,17,3,No,No,0,No,1,2.0
4,49,Female,Other,8.2,2.3,247,4,Yes,No,1,19,4,Yes,Yes,1,No,3,1.0

In [4]:
X = df.drop(columns=[TARGET])
y = df[TARGET]

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Train:", X_train.shape)
print("Val:", X_val.shape)

Train: (8800, 17)
Val: (2200, 17)

In [5]:
df.head()

,Age,Gender,Occupation,Sleep Hours,Physical Activity (hrs/week),Caffeine Intake (mg/day),Alcohol Consumption (drinks/week),Smoking,Family History of Anxiety,Stress Level (1-10),Breathing Rate (breaths/min),Sweating Level (1-5),Dizziness,Medication,Therapy Sessions (per month),Recent Major Life Event,Diet Quality (1-10),Anxiety Level (1-10)
0,29,Female,Artist,6.0,2.7,181,10,Yes,No,10,14,4,No,Yes,3,Yes,7,5.0
1,46,Other,Nurse,6.2,5.7,200,8,Yes,Yes,1,23,2,Yes,No,2,No,8,3.0
2,64,Male,Other,5.0,3.7,117,4,No,Yes,1,28,3,No,No,1,Yes,1,1.0
3,20,Female,Scientist,5.8,2.8,360,6,Yes,No,4,17,3,No,No,0,No,1,2.0
4,49,Female,Other,8.2,2.3,247,4,Yes,No,1,19,4,Yes,Yes,1,No,3,1.0

In [6]:
column_map = {
    "age": ["Age"],
    "gender": ["Gender"],
    "occupation": ["Occupation"],
    "sleep_hours": ["Sleep Hours"],
    "physical_activity": ["Physical Activity (hrs/week)"],
    "caffeine_intake": ["Caffeine Intake (mg/day)"],
    "alcohol_consumption": ["Alcohol Consumption (drinks/week)"],
    "smoking": ["Smoking"],
    "family_history_anxiety": ["Family History of Anxiety"],
    "stress_level": ["Stress Level (1-10)"],
    "breathing_rate": ["Breathing Rate (breaths/min)"],
    "sweating_level": ["Sweating Level (1-5)"],
    "dizziness": ["Dizziness"],
    "medication": ["Medication"],
    "therapy_sessions": ["Therapy Sessions (per month)"],
    "recent_life_event": ["Recent Major Life Event"],
    "diet_quality": ["Diet Quality (1-10)"]
}

In [7]:
pipeline = Pipeline([
    ("preprocessor", TherapeuticPreprocessor(column_map)),
    ("model", RandomForestRegressor(
        n_estimators=300,
        random_state=42
    ))
])

In [8]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 TherapeuticPreprocessor(column_map={'age': ['Age'],
                                                     'alcohol_consumption': ['Alcohol '
                                                                             'Consumption '
                                                                             '(drinks/week)'],
                                                     'breathing_rate': ['Breathing '
                                                                        'Rate '
                                                                        '(breaths/min)'],
                                                     'caffeine_intake': ['Caffeine '
                                                                         'Intake '
                                                                         '(mg/day)'],
                                                     'diet_quality': ['Diet '
                                                                      'Quality '
                                                                      '(1-10)'],
                                                     'dizziness': ['Dizziness'],
                                                     'family_history_anxiety': ['Family '
                                                                                'His...
                                                     'physical_activity': ['Physical '
                                                                           'Activity '
                                                                           '(hrs/week)'],
                                                     'recent_life_event': ['Recent '
                                                                           'Major '
                                                                           'Life '
                                                                           'Event'],
                                                     'sleep_hours': ['Sleep '
                                                                     'Hours'],
                                                     'smoking': ['Smoking'],
                                                     'stress_level': ['Stress '
                                                                      'Level '
                                                                      '(1-10)'],
                                                     'sweating_level': ['Sweating '
                                                                        'Level '
                                                                        '(1-5)'],
                                                     'therapy_sessions': ['Therapy '
                                                                          'Sessions '
                                                                          '(per '
                                                                          'month)']})),
                ('model',
                 RandomForestRegressor(n_estimators=300, random_state=42))])

In [9]:
val_preds = pipeline.predict(X_val)

mse = mean_squared_error(y_val, val_preds)
mae = mean_absolute_error(y_val, val_preds)
r2 = r2_score(y_val, val_preds)

print("Validation Results")
print("MSE :", mse)
print("MAE :", mae)
print("R2  :", r2)

Validation Results
MSE : 1.0312651616161614
MAE : 0.8179757575757576
R2  : 0.7774413656758512

In [10]:
ARTIFACT_PATH = PROJECT_ROOT / "artifacts/anxiety_classification/anxiety_pipeline.joblib"
ARTIFACT_PATH.parent.mkdir(exist_ok=True)

joblib.dump(pipeline, ARTIFACT_PATH)

print("Pipeline saved at:", ARTIFACT_PATH)

Pipeline saved at: C:\Users\A I TECH\Project\SentiCare-Capstone\artifacts\anxiety_classification\anxiety_pipeline.joblib

In [11]:
sample = X_val.iloc[:1]
prediction = pipeline.predict(sample)

print("Sample Prediction:", prediction)

Sample Prediction: [5.51]

In [12]:
import preprocessing.pipeline as p
print(p.__file__)

C:\Users\A I TECH\Project\SentiCare-Capstone\preprocessing\pipeline.py

In [13]:
from preprocessing.pipeline import TherapeuticPreprocessor
import inspect
print(inspect.signature(TherapeuticPreprocessor.fit))

(self, X, y=None)